name: CI

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18.0'

    - name: Setup GO environment
      run: |
            go mod download
            go get -t .
    
    - name: Build go-ignore-cov
      run: |
            go build

    - name: Unit tests
      run: |
            go test ./... -coverprofile coverage.out -covermode count
            ./go-ignore-cov --file coverage.out

    - name: Quality Gate - Test coverage shall 100.0 %
      env:
          TESTCOVERAGE_THRESHOLD: "100.0"
      run: |
            echo "Quality Gate: checking test coverage is above threshold ..."
            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage : $totalCoverage %"
            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
                echo "OK"
            else
                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
                echo "Failed"
                exit 1
            fi
